### ISSUE TITLE
BoM question?

### ISSUE THREAD

**Issue by mikeamcbrien** [walttriano/Ender_3Pro_Switchwire#2]
In the BOM there is listed under fasteners a 6x6x3 spacer with no quantity, or specs, but I cannot find where it is located in the CAD diagrams can anyone help with this?

**Comment by walttriano** [comment]
The spacers are reused from the Ender 3 pro.  They are from the V-wheel assemblies.

**Comment by mikeamcbrien** [comment]
Thank you!
